services:
  caddy:
    image: ghcr.io/dmitrvk/dmitrvkml_caddy:latest
    networks:
      - dmitrvkml
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - $HOME/public:/srv/public
      - caddy_data:/data
      - caddy_config:/config

  app:
    image: ghcr.io/dmitrvk/dmitrvkml:latest
    networks:
      - dmitrvkml
    restart: always
    volumes:
      - $HOME/public:/app/public

volumes:
  caddy_data:
  caddy_config:

networks:
  dmitrvkml:
    external: true
    name: dmitrvkml
