FROM node:18 as builder

ARG API_URL

ENV REACT_APP_API_URL $API_URL

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM caddy:2.5.2

COPY Caddyfile /etc/caddy/Caddyfile

COPY --from=builder /app/build /srv
