services:
  frontend:
    restart: always
    image: ghcr.io/dmitrvk/dmitrvkml_frontend:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $HOME/public:/srv/public
      - $HOME/notifications/static:/srv/notifications/static
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dmitrvkml_network

  backend:
    restart: always
    image: ghcr.io/dmitrvk/dmitrvkml_backend:latest
    networks:
      - dmitrvkml_network
    volumes:
      - $HOME/public:/public

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  dmitrvkml_network:
    external: true
    name: dmitrvkml_network
