services:
  frontend:
    restart: always
    image: dmitrvkml_frontend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $HOME/public:/srv/public
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dmitrvkml_network

  backend:
    restart: always
    image: dmitrvkml_backend
    networks:
      - dmitrvkml_network

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  dmitrvkml_network:
    external: true
    name: dmitrvkml_network
