services:
  frontend:
    build:
      context: .
      args:
        API_URL: 'http://localhost:8000/api'
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src

  backend:
    build: ./api
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
